---
- name: Check routing
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:

    - debug:
        msg: "{{city }} {{ device }}"

    - name: Send notification message via Mattermost all options
      community.general.mattermost:
        #url: https://10.10.101.115/hooks/kkhs7gmni3nmd85a38aor69czo
        url: https://10.10.101.115
        api_key: "kkhs7gmni3nmd85a38aor69czo"
        text: '{{ inventory_hostname }} completed'
        channel: "off-topic"
        priority: important
        validate_certs: false
        username: system-bot
